// es un lenguaje de progra y no es lo mismo que Java


console.log("hola mundo"); 
// - mostrar mensaje en la consola del navegador 

function mostrar(){

}
// las funciones parentesis y llave

// let nombre="Genesis"

// console.log(nombre);


let Nombre = "Genesis"; //String
let Apellido = "Garita";
let Edad = 25 //Integr o decimal sin comillas 
let Direccion = "Vargas Araya";
let Ventana
let Mensaje = "Hola mi nombre es:"+Nombre+ " y mi apellido es "+Apellido+" mi edad es "+Edad+" vivo en "+Direccion
let Mensaje2 ="Ess mayor de edad?"
console.log("Mensaje")
let TieneGatos = false //true o false es booleno
let TieneMascotas = true

let Frutas = ["Manzana", "Pera", "Uva"] //arreglo o array es una lista de variables 
let Persona = {
    //llave : valor
    nombre:"Genesis",
    edad: 29,
    TieneMascotas: true
}


// console.log(Apellido);
// console.log(Edad);
// console.log(Direccion);
// alert(Mensaje)
// Ventana=prompt(Mensaje2)
// alert(Ventana)


