// es un lenguaje de progra y no es lo mismo que Java


console.log("hola mundo"); 
// - mostrar mensaje en la consola del navegador 

function mostrar(){

}
// las funciones parentesis y llave

// let nombre="Genesis"

// console.log(nombre);


let Nombre = "Genesis";
let Apellido = "Garita";
let Edad = 25
let Direccion = "Vargas Araya";


console.log("Hola mi nombre es:"+Nombre+ " y mi apellido es "+Apellido+" mi edad es "+Edad+" vivo en "+Direccion);
// console.log(Apellido);
// console.log(Edad);
// console.log(Direccion);