// es un lenguaje de progra y no es lo mismo que Java


console.log("hola mundo"); 
// - mostrar mensaje en la consola del navegador 

function mostrar(){

}
// las funciones parentesis y llave

// let nombre="Genesis"

// console.log(nombre);


let Nombre = "Genesis";
let Apellido = "Garita";
let Edad = 25
let Direccion = "Vargas Araya";
let Ventana
let Mensaje = "Hola mi nombre es:"+Nombre+ " y mi apellido es "+Apellido+" mi edad es "+Edad+" vivo en "+Direccion
let Mensaje2 ="Ess mayor de edad?"
console.log("Mensaje")


// console.log(Apellido);
// console.log(Edad);
// console.log(Direccion);
// alert(Mensaje)
Ventana=prompt(Mensaje2)
alert(Ventana)


